builds:
  - binary: mediumautopost
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: mschmitt61
    homepage: "https://github.com/mschmitt61/vaultenv"
    tap:
      owner: mschmitt61
      name: homebrew-mschmitt61
    commit_author:
      name: mschmitt61
      email: mschmitt61@massmutual.com

checksum:
  name_template: 'checksums.txt'